FROM mcr.microsoft.com/devcontainers/base:bookworm

# Copy the generator script to PATH
COPY .devcontainer/iam_identity_center_generator.sh /usr/local/bin/iam_identity_center_generator
RUN chmod +x /usr/local/bin/iam_identity_center_generator
